name: CI

on:
  push:
  pull_request:

jobs:
  host:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        ruby:
        - '3.4'
        - '3.3'
        - '3.2'
        - '3.1'
        - '3.0'
        - '2.7'
        - '2.6'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: ruby --version

      - run: bundle exec rake
